-- Stop exposing every user's email, phone and full name to anonymous visitors.
--
-- 20250922000000_expertise_marketplace_schema.sql created:
--   CREATE POLICY "Public profiles are viewable by everyone"
--     ON public.profiles FOR SELECT USING (true);
--
-- With that in place, `GET /rest/v1/profiles?select=email,phone,full_name`
-- returns the entire user table to anyone holding the anon key (which ships in
-- the browser bundle). Verified against the live project.
--
-- RLS policies are OR'ed, so dropping this one leaves the access the app
-- actually relies on intact:
--   * "Users can view own profile"  -> auth.uid() = id
--     (20250921102746_b90ecc85-76ac-432c-b230-dd48ef6c28cf.sql)
--   * "Admins can view all profiles" -> public.is_admin()
--     (20260708160000_add_admin_profile_policies.sql)
--
-- Audited callers of public.profiles before writing this: AuthProvider,
-- Settings, ExpertOnboarding, userUtils and lib/auth all read only the signed-in
-- user's own row; every cross-user read (UserManagement, PlatformModeration,
-- ExpertApproval, AnalyticsDashboard, AdminDashboard) is admin-only and covered
-- by is_admin(). The single non-admin cross-user reader, components/ReviewList,
-- is not imported anywhere and renders nowhere in the app.

DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
