// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jctawltvlnooqqkltjvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjdGF3bHR2bG5vb3Fxa2x0anZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjE2NTksImV4cCI6MjA3MDU5NzY1OX0.wOLvpRoG_bkqdLgIw2tLY6FKJLKVAYwGZZtw1clkPfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});